version: "3"
services:
  panoptic_container:
    container_name: panoptic_container
    runtime: nvidia
    build: .
    shm_size: '256gb'
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "11452:22"
      - "8888"
      - "6006"
    tty: true
    volumes:
      - ~/datadir:/workspace/datadir
