version: "3"
services:
  minimum_container:
    container_name: testcontainer
    runtime: nvidia
    build: .
    shm_size: '16gb'
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "11451:22"
      - "8888"
      - "6006"
    tty: true
    volumes:
      - ~/datadir:/workspace/datadir