version: "3"
services:
  tensorrt_test:
    container_name: trtcontainer
    runtime: nvidia
    build: .
    shm_size: '32gb'
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "22"
      - "8888"
    tty: true
    volumes:
      - /home/takahiro/datadir:/workspace/datadir

