version: "3"
services:
  tensorrt_test:
    #container_name: mlcontainer
    runtime: nvidia
    build: .
    shm_size: '16gb'
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "11451:22"
      - "8888"
    tty: true
    volumes:
      - /home/takahiro/datadir:/workspace/datadir

