version: "3"
services:
  minimum_container:
    container_name: testcontainer
    runtime: nvidia
    build: .
    shm_size: '16gb'
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "10000:22"
      - "8888"
    tty: true
    volumes:
      - /home/takahiro/datadir:/workspace/datadir

