version: "3"
services:
  torch_jupyter:
    #container_name: mlcontainer
    runtime: nvidia
    build: .
    shm_size: '16gb'
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - 8888
      - 10000:22
    tty: true
    volumes:
      - /home/takahiro/datadir:/workspace/datadir

